### ISSUE TITLE
Figure out Layers

### ISSUE THREAD

**Issue by SirPurrcival** [SirPurrcival/mu-internship#10]
- How many neurons in each layer
- Connection probabilities between and in layers
- Figure out which parameters are important (also layer differences?)

**Comment by krisevers** [comment]
https://link.springer.com/article/10.1007/s00429-017-1554-4#Sec16 << especially Suppl. Mat. of this paper gives us a good estimate of the relative thickness of the layers.

https://1drv.ms/x/s!Al9x302PHHgxhLgJq6-QcX8JPB5eiw?e=WyUvck >> I made this document a while ago. I tried to make an overview of the laminar population sizes of each cell type (1 excitatory: PYR, and 3 inhibitory types: PV, SST, VIP) but didn't finish. So bare in mind this document isn't finished. 
I also added a connectivity profile of the interlaminar connections with some references. These probabilities mainly come from Billeh et al. (2020).

**Comment by fionaborska** [comment]
Schmidt et al. (2018) completely integrated. We have currently have the following information:

- Neuron density per layer per cell type (from Pfeffer et al. 2013)
- Percentage and number of inhibitory neurons, distribution of types of inhibitory cells (Meyer et al. 2011, 2010, Xu et al. 2010)
- Connection probability matrix of layers per cell type (Billeh et al. 2020)
- Number of (excitatory and inhibitory) extrinsic and intrinsic (self-connected) synapses in macaque V1 (Schmidt et al. 2018)
- Relative thickness of layers L1-L6 averaged from 4 different anatomical studies of macaque V1 (Schmidt et al. 2018)
- Thickness of layers L1-L6 in millimeters (Schmidt et al. 2018)
- Estimated excitatory and inhibitory population size for each layer L23-L6 (Schmidt et al. 2018)
