### ISSUE TITLE
Model building with the allen institute

### ISSUE THREAD

**Issue by SirPurrcival** [SirPurrcival/mu-internship#12]
- sample from neuron parameters of the allen institute for each neuron in the population of that layer (populaton sizes are available)
- assign connection probabilites according to connection probability matrix 
-

**Comment by fionaborska** [comment]
https://onedrive.live.com/view.aspx?resid=31781C8F4DDF715F!72713&ithint=file%2cxlsx&authkey=!AKuvkHF_CTweXos

Sheet with connectivity matrix, population sizes, laminar thickness, and cell type information

**Comment by fionaborska** [comment]
Population sizes & **all sets of parameters** per cell type per layer PYTHONIZED ->>> almost_there.py file uploaded to the experimental branch
