### ISSUE TITLE
I dont want to LIF anymore

### ISSUE THREAD

**Issue by SirPurrcival** [SirPurrcival/mu-internship#7]
Use GLIF. Read the GLIF paper and try to understand the parameters.
https://nest-simulator.readthedocs.io/en/stable/auto_examples/glif_psc_neuron.html?highlight=glif_psc%20example

https://nest-simulator.readthedocs.io/en/stable/models/glif_psc.html?highlight=glif_psc#id1

https://www.nature.com/articles/s41467-017-02717-4#Sec16

**Comment by krisevers** [comment]
conductance based GLIF >>> https://nest-simulator.readthedocs.io/en/stable/auto_examples/glif_cond_neuron.html (example)
current based GLIF          >>> https://nest-simulator.readthedocs.io/en/stable/models/glif_psc.html (documentation)

current vs conductance explained: https://neuronaldynamics.epfl.ch/online/Ch13.S6.html

What do current models with GLIF use?
Billeh et al. (2020) https://doi.org/10.1016/j.neuron.2020.01.040 >>> glif_psc
Chen et al. (2022) https://doi.org/10.1126/sciadv.abq7592          >>> glif_psc

**Comment by fionaborska** [comment]
This issue updated and overwritten by the new Allen Institute issue ( https://github.com/SirPurrcival/mu-internship/issues/12 )
